/*
 * English route. Generated by scripts/generate-en-routes.py — edit the
 * Bengali page at app/(public)/search instead, then re-run it.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */

import BengaliPage from '../../(public)/search/page';
import { metadata as bengaliMeta } from '../../(public)/search/page';
import { englishMetadata } from '@/lib/i18n/metadata';

export const metadata = englishMetadata(bengaliMeta, '/search');
export default function EnglishPage(props: any) {
  // The same component, told which language to render in.
  return <BengaliPage {...props} locale="en" />;
}
