"""Generates the /en route tree from the (public) pages.

Each English route re-exports the Bengali page implementation, so there is one
page per URL pair and no copy to keep in step. Metadata is the exception: it is
wrapped so the English URL is its own canonical.
"""
import pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'app'
public = root / '(public)'
en = root / 'en'

# Regex literal emitted into the generated file; kept out of an f-string so
# Python does not try to interpret its backslashes.
REPLACER = '/' + chr(92) + '[(' + chr(92) + 'w+)' + chr(92) + ']/g'

EXPORT_NAMES = ['metadata', 'generateMetadata', 'revalidate', 'dynamic', 'generateStaticParams']

made = []
for page in sorted(public.rglob('page.tsx')):
    rel = page.relative_to(public).parent          # e.g. blog/[slug]
    source = page.read_text(encoding='utf-8')

    present = [n for n in EXPORT_NAMES
               if re.search(rf'export (?:const|async function|function) {n}\b', source)]

    target_dir = en / rel
    target_dir.mkdir(parents=True, exist_ok=True)

    # Import path back to the Bengali page, from inside app/en/...
    depth = len(rel.parts)
    up = '../' * (depth + 1)
    src_import = f"{up}(public)/{'/'.join(rel.parts) + '/' if rel.parts else ''}page"

    bengali_path = '/' + '/'.join(rel.parts)
    lines = [
        '/*',
        ' * English route. Generated by scripts/generate-en-routes.mjs — edit the',
        f" * Bengali page at app/(public){bengali_path or '/'} instead, and re-run it.",
        ' *',
        ' * The page implementation is shared; only the metadata differs, so the',
        ' * English URL is its own canonical rather than pointing at the Bengali one.',
        ' */',
        f"export {{ default }} from '{src_import}';",
    ]

    for name in present:
        if name in ('revalidate', 'dynamic', 'generateStaticParams'):
            lines.append(f"export {{ {name} }} from '{src_import}';")

    if 'metadata' in present:
        lines += [
            f"import {{ metadata as bengali }} from '{src_import}';",
            "import { englishMetadata } from '@/lib/i18n/metadata';",
            '',
            f"export const metadata = englishMetadata(bengali, '{bengali_path or '/'}');",
        ]

    if 'generateMetadata' in present:
        lines += [
            f"import {{ generateMetadata as bengaliMetadata }} from '{src_import}';",
            "import { englishMetadata } from '@/lib/i18n/metadata';",
            '',
            '/* eslint-disable @typescript-eslint/no-explicit-any */',
            'export async function generateMetadata(props: any) {',
            '  const base = await (bengaliMetadata as any)(props);',
            '  const params = props?.params ? await props.params : {};',
        "  const path = '" + (bengali_path or '/') + "'.replace(" + REPLACER + ", (_m, key) => params[key] ?? '');",
            '',
            '  return englishMetadata(base, path);',
            '}',
        ]

    (target_dir / 'page.tsx').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    made.append(str(rel) or '(root)')

# Shared layout for the English tree.
(en / 'layout.tsx').write_text(
    '/*\n'
    ' * English shell. Reuses the public layout so the header, footer and their\n'
    ' * data fetching exist once; the locale itself comes from the URL.\n'
    ' */\n'
    "export { default } from '../(public)/layout';\n",
    encoding='utf-8',
)

print(f'{len(made)} English routes generated')
for m in made[:8]:
    print('  ', m)