"""Generates the /en route tree from the (public) pages.

Each English route renders the same page component with `locale="en"`, so there
is one implementation per URL pair and no copy to keep in step. Two things
differ per language:

  - the metadata, so an English page is its own canonical rather than declaring
    the Bengali URL and asking to be treated as a duplicate;
  - the locale prop, which the page uses to pick its dictionary.

Passing the locale keeps the pages statically renderable. Reading it from a
request header would work too, but it would opt every public page out of static
rendering for the sake of one string.

Run: python scripts/generate-en-routes.py
"""
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'app'
public = root / '(public)'
en = root / 'en'

# Emitted into the generated file; kept out of an f-string so Python does not
# try to interpret its backslashes.
PARAM_PATTERN = '/' + chr(92) + '[(' + chr(92) + 'w+)' + chr(92) + ']/g'

PASSTHROUGH = ['revalidate', 'dynamic', 'generateStaticParams']

made = []

for page in sorted(public.rglob('page.tsx')):
    rel = page.relative_to(public).parent
    source = page.read_text(encoding='utf-8')

    def exports(name):
        return re.search(rf'export (?:const|async function|function) {name}\b', source)

    target_dir = en / rel
    target_dir.mkdir(parents=True, exist_ok=True)

    depth = len(rel.parts)
    src_import = ('../' * (depth + 1)) + '(public)/' + ('/'.join(rel.parts) + '/' if rel.parts else '') + 'page'
    bengali_path = '/' + '/'.join(rel.parts)

    header = [
        '/*',
        ' * English route. Generated by scripts/generate-en-routes.py — edit the',
        f" * Bengali page at app/(public){bengali_path or '/'} instead, then re-run it.",
        ' */',
        '/* eslint-disable @typescript-eslint/no-explicit-any */',
    ]

    imports = [f"import BengaliPage from '{src_import}';"]
    body = []

    if exports('metadata'):
        imports.append(f"import {{ metadata as bengaliMeta }} from '{src_import}';")
    if exports('generateMetadata'):
        imports.append(f"import {{ generateMetadata as bengaliMeta }} from '{src_import}';")
    if exports('metadata') or exports('generateMetadata'):
        imports.append("import { englishMetadata } from '@/lib/i18n/metadata';")

    for name in PASSTHROUGH:
        if exports(name):
            body.append(f"export {{ {name} }} from '{src_import}';")

    if exports('metadata'):
        body.append(f"export const metadata = englishMetadata(bengaliMeta, '{bengali_path or '/'}');")

    if exports('generateMetadata'):
        body += [
            'export async function generateMetadata(props: any) {',
            '  // The locale goes to the page metadata too: a title built from',
            '  // interface words rather than from content needs to know.',
            "  const base = await (bengaliMeta as any)({ ...props, locale: 'en' });",
            '  const params = props?.params ? await props.params : {};',
            "  const path = '" + (bengali_path or '/') + "'.replace(" + PARAM_PATTERN + ", (_m, key) => params[key] ?? '');",
            '',
            '  return englishMetadata(base, path);',
            '}',
        ]

    body += [
        'export default function EnglishPage(props: any) {',
        '  // The same component, told which language to render in.',
        '  return <BengaliPage {...props} locale="en" />;',
        '}',
    ]

    lines = header + [''] + imports + [''] + body
    (target_dir / 'page.tsx').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    made.append(str(rel) or '(root)')

(en / 'layout.tsx').write_text(
    '/*\n'
    ' * English shell. Reuses the public layout so the header, footer and their\n'
    ' * data fetching exist once; the locale itself comes from the URL.\n'
    ' */\n'
    "export { default } from '../(public)/layout';\n",
    encoding='utf-8',
)

print(f'{len(made)} English routes generated')
