/*
 * English route. Generated by scripts/generate-en-routes.mjs — edit the
 * Bengali page at app/(public)/ instead, and re-run it.
 *
 * The page implementation is shared; only the metadata differs, so the
 * English URL is its own canonical rather than pointing at the Bengali one.
 */
export { default } from '../(public)/page';
import { metadata as bengali } from '../(public)/page';
import { englishMetadata } from '@/lib/i18n/metadata';

export const metadata = englishMetadata(bengali, '/');
