/*
 * English route. Generated by scripts/generate-en-routes.py — edit the
 * Bengali page at app/(public)/verify/[verificationId] instead, then re-run it.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */

import BengaliPage from '../../../(public)/verify/[verificationId]/page';
import { generateMetadata as bengaliMeta } from '../../../(public)/verify/[verificationId]/page';
import { englishMetadata } from '@/lib/i18n/metadata';

export async function generateMetadata(props: any) {
  // The locale goes to the page metadata too: a title built from
  // interface words rather than from content needs to know.
  const base = await (bengaliMeta as any)({ ...props, locale: 'en' });
  const params = props?.params ? await props.params : {};
  const path = '/verify/[verificationId]'.replace(/\[(\w+)\]/g, (_m, key) => params[key] ?? '');

  return englishMetadata(base, path);
}
export default function EnglishPage(props: any) {
  // The same component, told which language to render in.
  return <BengaliPage {...props} locale="en" />;
}
