import { test, expect } from '@playwright/test';

test('student registration, switching, course authoring and protected lesson files', async ({ page, browser }) => {
  test.skip(!process.env.E2E_LMS_ADMIN_PASSWORD, 'Requires an explicitly configured local Laravel stack and admin password.');
  test.setTimeout(180_000);
  const suffix = Date.now();
  const email = `lms-${suffix}@example.com`;
  await page.goto('/register');
  await expect(page.getByText('Student account', { exact: true })).toBeVisible();
  await expect(page.getByText('Ecommerce account', { exact: true })).toBeVisible();
  await page.locator('[name=name]').fill('LMS Test Student');
  await page.locator('[name=email]').fill(email);
  await page.locator('[name=password]').fill('Learning-Test-78432!');
  await page.locator('[name=password_confirmation]').fill('Learning-Test-78432!');
  await page.locator('[name=accepts_terms]').check();
  await page.locator('button[type=submit]').click();
  await expect(page).toHaveURL(/\/account$/);
  await expect(page.getByText('STUDENT • LEARNING MANAGEMENT SYSTEM')).toBeVisible();
  await page.getByRole('button', { name: 'Ecommerce', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Ecommerce', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByText('STUDENT • LEARNING MANAGEMENT SYSTEM')).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('button', { name: 'Ecommerce', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Student', exact: true }).click();
  await expect(page.getByText('STUDENT • LEARNING MANAGEMENT SYSTEM')).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('student-dashboard.png'), fullPage: true });

  const admin = await browser.newContext({ baseURL: process.env.E2E_BASE_URL });
  const request = admin.request;
  await request.get('/sanctum/csrf-cookie', { headers: { Origin: process.env.E2E_BASE_URL! } });
  const xsrf = decodeURIComponent((await admin.cookies()).find((cookie) => cookie.name === 'XSRF-TOKEN')!.value);
  const headers = { Origin: process.env.E2E_BASE_URL!, 'X-XSRF-TOKEN': xsrf };
  const login = await request.post('/api/v1/auth/login', { headers, data: { email: 'admin@nuruzzaman.com.bd', password: process.env.E2E_LMS_ADMIN_PASSWORD } });
  expect(login.ok(), await login.text()).toBeTruthy();
  const owner = await admin.newPage();
  await owner.goto('/dashboard/courses/new');
  const details = owner.locator('form').filter({ has: owner.locator('[name=description_markdown]') });
  await details.locator('[name=title]').fill(`LMS verification ${suffix}`);
  await details.locator('[name=slug]').fill(`lms-verification-${suffix}`);
  await details.locator('[name=description_markdown]').fill('Course created by the automated LMS workflow check.');
  await details.locator('[type=submit]').click();
  await expect(owner).toHaveURL(/\/dashboard\/courses\/\d+$/);
  const courseId = Number(owner.url().split('/').pop());
  const section = owner.locator('form').filter({ has: owner.locator('[name=title]') }).filter({ hasNot: owner.locator('[name=slug]') }).filter({ hasNot: owner.locator('[name=body_markdown]') }).first();
  await section.locator('[name=title]').fill('First module');
  await section.locator('[type=submit]').click();
  const lesson = owner.locator('#lesson-editor');
  await expect(lesson).toBeVisible();
  await lesson.locator('[name=title]').fill('First video lesson');
  await lesson.locator('[name=slug]').fill('first-video');
  await lesson.locator('[name=video_url]').fill('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
  await lesson.locator('[name=body_markdown]').fill('Download the attached practice notes.');
  const created = owner.waitForResponse((response) => response.url().endsWith(`/courses/${courseId}/lessons`) && response.request().method() === 'POST');
  await lesson.locator('[type=submit]').click();
  const lessonResponse = await created;
  expect(lessonResponse.ok(), await lessonResponse.text()).toBeTruthy();
  const lessonId = (await lessonResponse.json()).data.id;
  const upload = owner.waitForResponse((response) => response.url().endsWith(`/lessons/${lessonId}/assets`) && response.request().method() === 'POST');
  await owner.locator('input[type=file]').first().setInputFiles({ name: 'practice-notes.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nPractice notes for the LMS verification.') });
  const uploaded = await upload;
  expect(uploaded.ok(), await uploaded.text()).toBeTruthy();
  const assetId = (await uploaded.json()).data.id;
  await expect(owner.getByText(/practice-notes.pdf/).first()).toBeVisible();
  await owner.screenshot({ path: test.info().outputPath('course-editor.png'), fullPage: true });
  const users = await request.get(`/api/v1/admin/users?q=${encodeURIComponent(email)}`, { headers });
  const userId = (await users.json()).data.find((user: { email: string }) => user.email === email).id;
  const enrollment = await request.post('/api/v1/admin/enrollments', { headers, data: { user_id: userId, course_slug: `lms-verification-${suffix}`, reason: 'Automated workflow verification' } });
  expect(enrollment.ok(), await enrollment.text()).toBeTruthy();
  await page.goto(`/learn/lms-verification-${suffix}/first-video`);
  await expect(page.getByRole('heading', { name: 'First video lesson' })).toBeVisible();
  await expect(page.locator('iframe')).toHaveAttribute('src', 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ');
  const fileResponse = await page.request.get(`/api/v1/learn/lms-verification-${suffix}/lessons/first-video/assets/${assetId}`);
  expect(fileResponse.ok()).toBeTruthy();
  expect((await fileResponse.body()).toString()).toContain('Practice notes');
  const stranger = await browser.newContext({ baseURL: process.env.E2E_BASE_URL });
  expect((await stranger.request.get(`/api/v1/learn/lms-verification-${suffix}/lessons/first-video/assets/${assetId}`, { headers: { Accept: 'application/json' } })).status()).toBe(401);
  await stranger.close();
  await request.post(`/api/v1/admin/courses/${courseId}/transition`, { headers, data: { status: 'archived' } });
  await admin.close();
});
