/*
 * English route. Generated by scripts/generate-en-routes.mjs — edit the
 * Bengali page at app/(public)/support instead, and re-run it.
 *
 * The page implementation is shared; only the metadata differs, so the
 * English URL is its own canonical rather than pointing at the Bengali one.
 */
export { default } from '../../(public)/support/page';
import { generateMetadata as bengaliMetadata } from '../../(public)/support/page';
import { englishMetadata } from '@/lib/i18n/metadata';

/* eslint-disable @typescript-eslint/no-explicit-any */
export async function generateMetadata(props: any) {
  const base = await (bengaliMetadata as any)(props);
  const params = props?.params ? await props.params : {};
  const path = '/support'.replace(/\[(\w+)\]/g, (_m, key) => params[key] ?? '');

  return englishMetadata(base, path);
}
